[project]
name = "project"
version = "0.1.0"
description = "RAG pipeline for indexing and searching GitHub markdown repositories"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "groq>=1.1.1",
    "minsearch>=0.0.10",
    "python-frontmatter>=1.1.0",
    "requests>=2.32.5",
    "sentence-transformers>=5.3.0",
    "tqdm>=4.67.3",
]

[dependency-groups]
dev = [
    "black>=26.3.1",
    "isort>=8.0.1",
    "ruff>=0.15.8",
]
